ATENÇÃO SADIA
PRODUTOS DA SADIA
EU, TULLA LUANA FONTES DOS SANTOS, CELEBRIDADE DA INTERNET, WEBCELEBRIDADE QUE JAMAIS DEIXAREI DE SER COMO WEBDIVA TULLA LUANA
QUERO OS MEUS MASCOTES DA PROMOÇÃO SADIA. "AH, VÁ AO POSTO DE TROCA MAIS PRÓXIMO" NÃO TEM, CARALHO! O POSTO MAIS PRÓXIMO EM EM
NOVA ODESSA. EU MORO EM SUMARÉ, SÃO PAULO. QUE PROMOÇÃO É ESSA, SADIA, ENGANOSA? SERÁ QUE EU TENHO QUE ESTAR ENSINANDO TUDO PARA
VOCÊS? ME CONTRATEM, EMPRESAS, ME CONTRATEM. GORDINHA FICA ASSIM NA COXIA, PODE MUITO BEM ORIENTAR VOCÊS. "AH, NÃO PODE PORQUE VOCÊ
  É ESQUIZOFRÊNICA" MAS EU SOU INTELIGENTE! SE VOCÊS FAZEM ESSSA PROMOÇÃO A NÍVEL  BRASIL, EM CADA CIDADE QUE VOCÊS VENDEREM OS
  PRODUTOS TEM QUE TER UM POSTO DE TROCA.
